import type { CaseSummary, SessionDebrief } from '../domain/types'

export const seededCases: CaseSummary[] = [
  {
    id: '1',
    code: 'NEU-017',
    title: 'Acute posterior circulation stroke workup',
    subspecialty: 'Neuroradiology',
    modality: 'CTA Head/Neck',
    difficulty: 'Standard',
    duration: '12 min',
    objective: 'Practice observation, synthesis, and urgent management communication for posterior circulation ischemia.',
    vignette: '65-year-old with sudden vertigo, diplopia, and gait instability. Review CTA and state the most likely diagnosis and immediate management priorities.',
    findings: ['Occlusion of the left vertebral artery V4 segment', 'Diminished basilar tip opacification', 'No large parenchymal hemorrhage on non-contrast images'],
    differential: ['Basilar thromboembolic disease', 'Severe vertebrobasilar atherosclerotic stenosis'],
    management: ['Activate stroke team', 'Recommend urgent neurointerventional evaluation', 'Clarify hemorrhage exclusion before thrombolysis discussion'],
    examinerOpening: 'You are covering stroke CTA overnight. Start with the immediately actionable finding, then tell me what you would communicate right now.',
    hiddenDiagnosis: 'Acute posterior circulation thromboembolic occlusion with vertebrobasilar threat.',
    keyTeachingPoint: 'Name the vascular lesion, explain why it is dangerous, and give the escalation path succinctly.',
    candidateTasks: ['Identify the major abnormality and pertinent negative findings.', 'State the most likely diagnosis and a reasonable alternative.', 'Recommend the immediate escalation pathway in board-style language.'],
    observationChecklist: ['Recognizes distal vertebral occlusion', 'Mentions reduced basilar tip opacification', 'Confirms no large hemorrhage on companion non-contrast imaging'],
    synthesisChecklist: ['Prioritizes posterior circulation thromboembolism', 'Mentions a plausible alternative process', 'Connects imaging findings to neurologic risk'],
    managementChecklist: ['Communicates stroke-team urgency', 'Names neurointerventional escalation', 'Notes hemorrhage exclusion relevance'],
    examinerPrompts: {
      interpretation: 'Tighten the interpretation. What is the major vascular lesion and what pertinent negative do you need from the companion study?',
      differential: 'Give me your leading diagnosis and one reasonable alternative, but rank them.',
      management: 'Now tell me exactly who you would call and why this cannot wait.',
      closing: 'End with the one-line board answer you would put in a critical communication.',
    },
    practicalNotes: ['MRI sequence-identification trivia is out of scope for this MVP.', 'Focus on clinical observation, synthesis, and management.'],
  },
  {
    id: '2',
    code: 'ABD-031',
    title: 'Threatened bowel in incarcerated inguinal hernia',
    subspecialty: 'Abdominal Imaging',
    modality: 'Abdominal radiographs + CT Abdomen/Pelvis',
    difficulty: 'Advanced',
    duration: '14 min',
    objective: 'Mirror ABR-style progression from initial observation to next-study recommendation and urgent management.',
    vignette: 'Young adult with vomiting and abdominal pain. Start from the abdominal radiographs, then discuss the next study and resulting management.',
    findings: ['Dilated gas-filled small bowel loops', 'No free intraperitoneal air', 'CT shows right inguinal hernia containing thickened hypoenhancing ileum'],
    differential: ['Closed loop small bowel obstruction', 'Ischemic bowel within incarcerated inguinal hernia'],
    management: ['Recommend contrast-enhanced CT after radiographs', 'Communicate concern for threatened bowel', 'Advise urgent surgical consultation'],
    examinerOpening: 'Describe the radiographs first. Tell me the key finding, the pertinent negative, and what study you want next.',
    hiddenDiagnosis: 'Ischemic bowel within an incarcerated right inguinal hernia causing small bowel obstruction.',
    keyTeachingPoint: 'A good oral answer progresses from observation to the next best test, then to urgency and disposition.',
    candidateTasks: ['Describe the initial radiographic pattern and pertinent negative.', 'Request and interpret the next most useful study.', 'State the presumptive diagnosis and urgent next step.'],
    observationChecklist: ['Recognizes small bowel obstruction pattern', 'Mentions absence of free air', 'Identifies thickened hypoenhancing bowel in the hernia on CT'],
    synthesisChecklist: ['Connects obstruction to incarcerated hernia', 'Raises bowel ischemia concern', 'Keeps a reasonable alternative in the differential'],
    managementChecklist: ['Requests CT appropriately', 'Uses urgent language for threatened bowel', 'Recommends surgical consultation'],
    examinerPrompts: {
      interpretation: 'What is your pertinent negative on the radiographs, and what subtle clue should make you search the groin carefully?',
      differential: 'Now that CT is available, rank the diagnosis and explain why viability is the issue.',
      management: 'What is the immediate recommendation, and how would you communicate urgency?',
      closing: 'Summarize this as if you were speaking to surgery on the phone.',
    },
    practicalNotes: ['Grounded in ABR-published examples of observation, synthesis, and management flow.', 'Built as educationally similar structure, not a reproduction of exam material.'],
  },
  {
    id: '3',
    code: 'MSK-008',
    title: 'Aggressive distal femur lesion with staging discussion',
    subspecialty: 'Musculoskeletal',
    modality: 'Radiographs + MRI Knee',
    difficulty: 'Standard',
    duration: '10 min',
    objective: 'Practice lesion characterization, prioritized malignant differential, and practical staging/referral recommendations.',
    vignette: '18-year-old with progressive knee pain and palpable mass. Review the available imaging and describe the lesion, differential, and staging workup.',
    findings: ['Aggressive metaphyseal distal femur lesion', 'Large soft tissue component', 'Cortical breakthrough with periosteal reaction'],
    differential: ['Osteosarcoma', 'Ewing sarcoma'],
    management: ['Recommend dedicated radiographs and chest CT', 'Advise orthopedic oncology referral', 'Avoid unplanned biopsy pathway'],
    examinerOpening: 'Characterize the lesion first like you are in a multidisciplinary conference, then give me the most likely diagnosis.',
    hiddenDiagnosis: 'Aggressive malignant bone tumor, most concerning for osteosarcoma.',
    keyTeachingPoint: 'The oral-board move is not just naming the tumor, it is giving the safest staging and referral path.',
    candidateTasks: ['Describe aggressive imaging features clearly.', 'Prioritize the malignant differential.', 'Recommend staging and referral steps that avoid a bad biopsy pathway.'],
    observationChecklist: ['Describes marrow-replacing metaphyseal lesion', 'Mentions cortical breakthrough and soft tissue mass', 'Uses aggressive lesion language'],
    synthesisChecklist: ['Ranks osteosarcoma highest', 'Includes another malignant bone tumor alternative', 'Connects age and imaging pattern to the differential'],
    managementChecklist: ['Recommends staging chest imaging', 'Names orthopedic oncology referral', 'Warns against unplanned biopsy'],
    examinerPrompts: {
      interpretation: 'Which imaging features make this aggressive rather than indeterminate?',
      differential: 'Rank the top two malignant considerations and defend the leading choice.',
      management: 'What staging workup and referral path do you recommend right now?',
      closing: 'Give me the concise report impression plus recommendation.',
    },
    practicalNotes: ['MRI sequences should be labeled in the eventual product, matching ABR guidance.', 'Keep the discussion clinically grounded, not trivia-driven.'],
  },
]

export const defaultDebrief: SessionDebrief = {
  disposition: 'Pass',
  summary: 'You identified the dangerous pattern and maintained a board-style structure. The next level is to rank the differential sooner and state management in one tight sentence.',
  strongAnswer: 'This study demonstrates an acute, high-risk process that warrants immediate escalation. I would name the leading diagnosis, mention the critical exclusion if relevant, and communicate the recommended specialty activation without delay.',
  nextSteps: [
    'Practice ranking your top two differentials before management.',
    'Keep one short escalation sentence ready for urgent cases.',
    'Run one more timed case in a different subspecialty this week.',
  ],
  scoreBreakdown: [
    { label: 'Observation', score: 4.4, note: 'Found the dangerous pattern quickly.' },
    { label: 'Synthesis', score: 4.0, note: 'Reasoning was solid but can tighten ranking.' },
    { label: 'Management', score: 4.6, note: 'Escalation pathway was appropriate.' },
    { label: 'Communication', score: 4.2, note: 'Stayed organized under pressure.' },
  ],
  overallScore: 84,
  criticalMisses: 0,
}
