import type { CaseSummary, SessionDebrief } from '../domain/types'

export const seededCases: CaseSummary[] = [
  {
    id: '1',
    code: 'NEU-017',
    title: 'Acute posterior circulation stroke workup',
    subspecialty: 'Neuroradiology',
    modality: 'CTA Head/Neck',
    difficulty: 'Standard',
    duration: '12 min',
    objective: 'Practice the ABR-style sequence of concise interpretation, ranked differential, and urgent management communication.',
    vignette: '65-year-old with sudden vertigo, diplopia, and gait instability. Review the CTA and discuss the most likely diagnosis and immediate management priorities.',
    history: 'Emergency department stroke evaluation with posterior circulation symptoms.',
    findings: ['Occlusion of the left vertebral artery V4 segment', 'Diminished basilar tip opacification', 'No large parenchymal hemorrhage on companion non-contrast imaging'],
    differential: ['Acute vertebrobasilar thromboembolic occlusion', 'High-grade vertebrobasilar atherosclerotic stenosis with slow flow'],
    management: ['Activate the stroke team immediately', 'Recommend urgent neurointerventional evaluation', 'Clarify hemorrhage exclusion before thrombolysis discussion'],
    examinerOpening: 'You are covering stroke CTA overnight. Start with the most actionable imaging finding and then tell me who you need to call.',
    hiddenDiagnosis: 'Acute posterior circulation thromboembolic occlusion with vertebrobasilar threat.',
    keyTeachingPoint: 'ABR-style answers stay brief, prioritize the dangerous lesion, and end with a specific escalation pathway.',
    candidateTasks: ['Identify the major abnormality and the pertinent negative finding.', 'Rank the most likely diagnosis and one alternative.', 'State the immediate management escalation in one concise sentence.'],
    observationChecklist: ['vertebral artery occlusion', 'basilar tip opacification', 'no hemorrhage'],
    synthesisChecklist: ['posterior circulation thromboembolism', 'atherosclerotic stenosis', 'high-risk posterior circulation ischemia'],
    managementChecklist: ['stroke team', 'neurointerventional', 'urgent'],
    examinerPrompts: {
      interpretation: 'Tighten the interpretation. What is the key vascular lesion, and what pertinent negative do you need from the companion study?',
      differential: 'Give me your leading diagnosis and one reasonable alternative, ranked.',
      management: 'Now tell me exactly who you would call and why this cannot wait.',
      closing: 'Close with the one-line report impression you would communicate urgently.',
    },
    examinerCues: [
      { when: 'opening', text: 'Examiner stance: concise neuroradiology oral board, not a tutorial.' },
      { when: 'after-interpretation', text: 'If the candidate is vague, redirect to the vessel and the time-sensitive risk.' },
      { when: 'after-differential', text: 'Demand ranking, not a loose list.' },
      { when: 'after-management', text: 'Push for one explicit critical communication statement.' },
    ],
    sampleAnswerFrame: ['Actionable finding first', 'Ranked diagnosis second', 'Urgent call and disposition third'],
    practicalNotes: ['Built to mirror public ABR discussion flow: identify, rank, act.'],
  },
  {
    id: '2',
    code: 'ABD-031',
    title: 'Threatened bowel in incarcerated inguinal hernia',
    subspecialty: 'Abdominal Imaging',
    modality: 'Radiographs + CT Abdomen/Pelvis',
    difficulty: 'Advanced',
    duration: '14 min',
    objective: 'Mirror ABR-style progression from initial radiographic observation to next-study recommendation and urgent surgical communication.',
    vignette: 'Young adult with vomiting and abdominal pain. Start from abdominal radiographs, then discuss the next study and resulting management.',
    history: 'Emergency department bowel obstruction workup.',
    findings: ['Dilated gas-filled small bowel loops', 'No free intraperitoneal air', 'CT shows right inguinal hernia containing thickened hypoenhancing ileum'],
    differential: ['Ischemic bowel within incarcerated inguinal hernia', 'Closed-loop small bowel obstruction without frank infarction'],
    management: ['Recommend contrast-enhanced CT after radiographs', 'Communicate concern for threatened bowel', 'Advise urgent surgical consultation'],
    examinerOpening: 'Describe the radiographs first. Give me the key finding, a pertinent negative, and what study you want next.',
    hiddenDiagnosis: 'Ischemic bowel within an incarcerated right inguinal hernia causing small bowel obstruction.',
    keyTeachingPoint: 'A strong board answer moves cleanly from image pattern to next study to disposition.',
    candidateTasks: ['Describe the initial radiographic pattern and pertinent negative.', 'Request and interpret the next most useful study.', 'State the presumptive diagnosis and urgent next step.'],
    observationChecklist: ['small bowel obstruction', 'no free air', 'hypoenhancing ileum'],
    synthesisChecklist: ['incarcerated hernia', 'bowel ischemia', 'closed-loop obstruction'],
    managementChecklist: ['contrast-enhanced ct', 'urgent surgical consultation', 'threatened bowel'],
    examinerPrompts: {
      interpretation: 'What is your pertinent negative on the radiographs, and what should prompt a careful search of the groin?',
      differential: 'Now that CT is available, rank the diagnosis and explain why viability is the issue.',
      management: 'What is the immediate recommendation, and how would you communicate urgency?',
      closing: 'Summarize this exactly as if you were speaking to the surgeon on the phone.',
    },
    examinerCues: [
      { when: 'opening', text: 'Examiner expects the candidate to walk from x-ray to CT, not jump past the sequence.' },
      { when: 'after-interpretation', text: 'Probe whether the candidate recognizes threatened bowel rather than obstruction alone.' },
      { when: 'after-differential', text: 'Keep the candidate ranked and decisive.' },
      { when: 'after-management', text: 'Require urgent surgical language.' },
    ],
    sampleAnswerFrame: ['Radiographic pattern', 'CT clarification', 'Threatened bowel and urgent surgery'],
    practicalNotes: ['Grounded in public ABR sample-case style where the examiner advances stepwise through available imaging.'],
  },
  {
    id: '3',
    code: 'MSK-008',
    title: 'Aggressive distal femur lesion with staging discussion',
    subspecialty: 'Musculoskeletal',
    modality: 'Radiographs + MRI Knee',
    difficulty: 'Standard',
    duration: '10 min',
    objective: 'Practice lesion characterization, prioritized malignant differential, and safe staging and referral recommendations.',
    vignette: '18-year-old with progressive knee pain and palpable mass. Review the available imaging and describe the lesion, differential, and staging workup.',
    history: 'Outpatient workup for suspected malignant bone lesion.',
    findings: ['Aggressive metaphyseal distal femur lesion', 'Large soft tissue component', 'Cortical breakthrough with periosteal reaction'],
    differential: ['Osteosarcoma', 'Ewing sarcoma'],
    management: ['Recommend chest CT for staging', 'Advise orthopedic oncology referral', 'Avoid unplanned biopsy pathway'],
    examinerOpening: 'Characterize the lesion first as if you are in multidisciplinary conference, then give me the most likely diagnosis.',
    hiddenDiagnosis: 'Aggressive malignant bone tumor, most concerning for osteosarcoma.',
    keyTeachingPoint: 'The board move is not just naming the tumor. It is protecting the patient with the right staging and referral path.',
    candidateTasks: ['Describe aggressive imaging features clearly.', 'Prioritize the malignant differential.', 'Recommend staging and referral steps that avoid a bad biopsy pathway.'],
    observationChecklist: ['aggressive metaphyseal lesion', 'soft tissue component', 'cortical breakthrough'],
    synthesisChecklist: ['osteosarcoma', 'ewing sarcoma', 'malignant bone tumor'],
    managementChecklist: ['chest ct', 'orthopedic oncology', 'avoid unplanned biopsy'],
    examinerPrompts: {
      interpretation: 'Which imaging features make this aggressive rather than indeterminate?',
      differential: 'Rank the top two malignant considerations and defend the leading choice.',
      management: 'What staging workup and referral path do you recommend right now?',
      closing: 'Give me the concise report impression plus recommendation.',
    },
    examinerCues: [
      { when: 'opening', text: 'Examiner voice stays like a radiologist, not an orthopedic oncologist.' },
      { when: 'after-interpretation', text: 'Insist on lesion characterization before naming pathology.' },
      { when: 'after-differential', text: 'Ask for ranking tied to age and appearance.' },
      { when: 'after-management', text: 'Push for safe staging and referral, not biopsy improvisation.' },
    ],
    sampleAnswerFrame: ['Aggressive lesion description', 'Ranked malignant differential', 'Staging and specialty referral'],
  },
  {
    id: '4',
    code: 'CHE-022',
    title: 'Tension physiology from traumatic chest injury',
    subspecialty: 'Thoracic Imaging',
    modality: 'Portable Chest Radiograph + CT Chest',
    difficulty: 'Standard',
    duration: '11 min',
    objective: 'Train rapid identification of immediately life-threatening chest imaging findings and concise escalation language.',
    vignette: 'Polytrauma patient becomes acutely hypotensive after line placement. Review the radiograph and chest CT findings and discuss management.',
    history: 'ICU portable chest radiograph followed by CT chest in an unstable trauma patient.',
    findings: ['Large right pneumothorax', 'Mediastinal shift to the left', 'Dependent right pleural fluid with associated rib fractures'],
    differential: ['Tension pneumothorax with associated hemothorax', 'Large simple pneumothorax without tension physiology'],
    management: ['Communicate tension physiology immediately', 'Recommend emergent decompression and chest tube placement', 'Alert trauma team to probable hemopneumothorax'],
    examinerOpening: 'Start with the portable chest radiograph. What is the immediately life-threatening finding and how are you communicating it?',
    hiddenDiagnosis: 'Traumatic right tension hemopneumothorax.',
    keyTeachingPoint: 'Public ABR-style case flow favors actionable observation first and avoids hedging when the patient is unstable.',
    candidateTasks: ['Identify the life-threatening finding on the radiograph.', 'Refine the diagnosis using the CT findings.', 'State the emergent management communication.'],
    observationChecklist: ['pneumothorax', 'mediastinal shift', 'pleural fluid'],
    synthesisChecklist: ['tension pneumothorax', 'hemopneumothorax', 'unstable trauma'],
    managementChecklist: ['emergent decompression', 'chest tube', 'trauma team'],
    examinerPrompts: {
      interpretation: 'Be specific. What makes this more than a routine pneumothorax?',
      differential: 'Rank the leading diagnosis and the less likely alternative.',
      management: 'Tell me your exact urgent communication to the trauma team.',
      closing: 'Give me a one-sentence impression and recommendation.',
    },
    examinerCues: [
      { when: 'opening', text: 'Examiner expects immediate action language.' },
      { when: 'after-interpretation', text: 'If the candidate hedges, redirect to tension physiology.' },
      { when: 'after-differential', text: 'Do not allow a broad unfocused chest trauma differential.' },
      { when: 'after-management', text: 'Demand a direct call-out recommendation.' },
    ],
    sampleAnswerFrame: ['Life-threatening chest finding', 'Why it represents tension physiology', 'Immediate trauma communication'],
  },
  {
    id: '5',
    code: 'BRE-011',
    title: 'Spiculated breast mass with axillary adenopathy',
    subspecialty: 'Breast Imaging',
    modality: 'Diagnostic Mammogram + Targeted Ultrasound',
    difficulty: 'Advanced',
    duration: '13 min',
    objective: 'Practice radiologist-style lesion description, BI-RADS-level synthesis, and biopsy recommendation language.',
    vignette: '52-year-old with palpable left breast lump. Review the mammographic and sonographic findings and discuss disposition.',
    history: 'Diagnostic workup of a palpable breast finding.',
    findings: ['Irregular spiculated high-density mass in the upper outer left breast', 'Targeted ultrasound shows a corresponding irregular hypoechoic mass', 'Abnormal left axillary lymph node with cortical thickening'],
    differential: ['Primary invasive breast carcinoma with nodal involvement', 'Post-inflammatory scar-like process, much less likely'],
    management: ['Recommend ultrasound-guided core biopsy of the breast mass', 'Recommend sampling of the suspicious axillary node', 'Communicate highly suspicious malignant appearance'],
    examinerOpening: 'Describe the mammogram first, then correlate the targeted ultrasound and tell me your level of concern.',
    hiddenDiagnosis: 'Highly suspicious breast malignancy with probable nodal metastatic disease.',
    keyTeachingPoint: 'The public ABR sample style emphasizes disciplined description, probability language, and next-step recommendation.',
    candidateTasks: ['Describe the lesion using breast imaging language.', 'State the most likely diagnosis and a much less likely alternative.', 'Recommend the next procedures and disposition.'],
    observationChecklist: ['spiculated mass', 'hypoechoic mass', 'axillary lymph node'],
    synthesisChecklist: ['invasive breast carcinoma', 'nodal involvement', 'highly suspicious malignant appearance'],
    managementChecklist: ['core biopsy', 'node sampling', 'high suspicion'],
    examinerPrompts: {
      interpretation: 'Use formal breast-imaging description. How would you characterize this lesion?',
      differential: 'What is the most likely diagnosis, and what is your much less likely alternative?',
      management: 'What do you recommend next, specifically?',
      closing: 'Close with a concise impression and recommendation in report language.',
    },
    examinerCues: [
      { when: 'opening', text: 'Examiner expects structured descriptor language and clear concern level.' },
      { when: 'after-interpretation', text: 'Probe for disciplined lexicon rather than generic wording.' },
      { when: 'after-differential', text: 'Require a dominant malignant diagnosis with one low-likelihood alternative.' },
      { when: 'after-management', text: 'Insist on biopsy pathway and nodal sampling.' },
    ],
    sampleAnswerFrame: ['Formal lesion description', 'Malignancy-first synthesis', 'Biopsy and node sampling recommendation'],
  },
]

export const defaultDebrief: SessionDebrief = {
  disposition: 'Pass',
  summary: 'You stayed organized and clinically focused. The next level is to make the first sentence more decisive and close with an explicit recommendation.',
  strongAnswer: 'State the key imaging abnormality first, rank the top diagnosis confidently, and finish with the exact escalation or biopsy recommendation.',
  nextSteps: [
    'Practice giving the impression before the explanation.',
    'Keep one alternative diagnosis ready, but clearly secondary.',
    'Close every case with a concrete next step.',
  ],
  scoreBreakdown: [
    { label: 'Observation', score: 4.4, note: 'Found the dangerous pattern quickly.' },
    { label: 'Synthesis', score: 4.0, note: 'Reasoning was solid but can tighten ranking.' },
    { label: 'Management', score: 4.6, note: 'Escalation pathway was appropriate.' },
    { label: 'Communication', score: 4.2, note: 'Stayed organized under pressure.' },
  ],
  overallScore: 84,
  criticalMisses: 0,
}
