import type { CaseSummary, SessionDebrief } from '../domain/types'

export const seededCases: CaseSummary[] = [
  {
    id: '1',
    code: 'NEU-017',
    title: 'Acute posterior circulation stroke workup',
    subspecialty: 'Neuroradiology',
    modality: 'CTA Head/Neck',
    difficulty: 'Standard',
    duration: '12 min',
    objective: 'Practice vascular localization, high-stakes communication, and thrombectomy triage.',
    vignette: '65-year-old with sudden vertigo, diplopia, and gait instability. Review CTA and state the most likely diagnosis and immediate management priorities.',
    findings: ['Occlusion of the left vertebral artery V4 segment', 'Diminished basilar tip opacification', 'No large parenchymal hemorrhage on non-contrast images'],
    differential: ['Basilar thromboembolic disease', 'Severe vertebrobasilar atherosclerotic stenosis'],
    management: ['Activate stroke team', 'Recommend urgent neurointerventional evaluation', 'Clarify hemorrhage exclusion before thrombolysis discussion'],
    examinerOpening: 'You are covering stroke CTA overnight. Start with the immediately actionable finding, then tell me what you would communicate right now.',
    hiddenDiagnosis: 'Acute posterior circulation thromboembolic occlusion with vertebrobasilar threat.',
    keyTeachingPoint: 'Name the vascular lesion, say why it is dangerous, and communicate the escalation pathway explicitly.',
  },
  {
    id: '2',
    code: 'ABD-031',
    title: 'Occult bowel ischemia on CT abdomen',
    subspecialty: 'Abdominal Imaging',
    modality: 'CT Abdomen/Pelvis',
    difficulty: 'Advanced',
    duration: '14 min',
    objective: 'Identify subtle ischemic signs and defend operative urgency.',
    vignette: '72-year-old with atrial fibrillation, pain out of proportion, and rising lactate. Interpret the contrast-enhanced CT and prioritize next steps.',
    findings: ['Segmental hypoenhancement of mid-small bowel', 'Mesenteric edema with trace free fluid', 'Abrupt SMA branch cutoff'],
    differential: ['Acute mesenteric ischemia', 'Closed loop obstruction with vascular compromise'],
    management: ['Urgent surgical consultation', 'Communicate bowel threat explicitly', 'Recommend CTA review and anticoagulation discussion in context'],
    examinerOpening: 'Describe the bowel and mesenteric findings first. Then tell me whether this can wait.',
    hiddenDiagnosis: 'Acute mesenteric ischemia with threatened bowel viability.',
    keyTeachingPoint: 'Subtle ischemia still demands decisive language and urgent escalation.',
  },
  {
    id: '3',
    code: 'MSK-008',
    title: 'Aggressive distal femur lesion',
    subspecialty: 'MSK',
    modality: 'MRI Knee',
    difficulty: 'Standard',
    duration: '10 min',
    objective: 'Structure malignant bone tumor differential and staging recommendations.',
    vignette: '18-year-old with progressive knee pain and palpable mass. Review MRI and describe the lesion, differential, and staging workup.',
    findings: ['Metaphyseal marrow replacing lesion in distal femur', 'Large soft tissue component', 'Periosteal reaction with cortical breakthrough'],
    differential: ['Osteosarcoma', 'Ewing sarcoma'],
    management: ['Recommend dedicated radiographs and chest CT', 'Advise orthopedic oncology referral', 'Avoid unplanned biopsy pathway'],
    examinerOpening: 'Characterize the lesion like you are speaking to the ABR examiner, then give me your highest-probability differential.',
    hiddenDiagnosis: 'Aggressive malignant bone tumor, most concerning for osteosarcoma.',
    keyTeachingPoint: 'Pattern recognition matters, but staging and referral pathway matter just as much.',
  },
]

export const defaultDebrief: SessionDebrief = {
  disposition: 'Pass',
  summary: 'You identified the dangerous pattern and maintained a board-style structure. The next level is to rank the differential sooner and state management in one tight sentence.',
  strongAnswer: 'This study demonstrates an acute, high-risk process that warrants immediate escalation. I would name the leading diagnosis, mention the critical exclusion if relevant, and communicate the recommended specialty activation without delay.',
  nextSteps: [
    'Practice ranking your top two differentials before management.',
    'Keep one short escalation sentence ready for vascular emergencies.',
    'Run one more timed case in a different subspecialty this week.',
  ],
  scoreBreakdown: [
    { label: 'Detection', score: 4.4, note: 'Found the dangerous pattern quickly.' },
    { label: 'Description', score: 4.1, note: 'Board-style language stayed crisp.' },
    { label: 'Differential', score: 3.8, note: 'Could rank alternatives earlier.' },
    { label: 'Management', score: 4.6, note: 'Escalation pathway was appropriate.' },
    { label: 'Communication', score: 4.2, note: 'Stayed organized under pressure.' },
  ],
  overallScore: 84,
  criticalMisses: 0,
}
